steps:
  # Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/kaviuln/image-10.2-app:$COMMIT_SHA",
        ".",
      ]

  # Docker Push
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/${PROJECT_ID}/kaviuln/image-10.2-app:$COMMIT_SHA']

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment/app-deployment', 'myapp-container=gcr.io/sit737-23t1-hossain-c94cda1/kaviuln/image-10.2-app:$COMMIT_SHA']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
